### PR TITLE
WIP: download regions specified in yaml

### LINKED ISSUE #93: Add new regions from remote url locations via yaml
https://www.marineregions.org/downloads.php

Implement with caching of download. See other issue.

### PR DESCRIPTION
**Pull request by aaronspring**
First I wanted to include only the Longhurst regions. Then, I got disappointed because I did find this shapefile to be downloaded by a script only without any agreement to whatever. Assuming that we are also fine with users manually downloading a few datasets with instructions (given in yaml), `regionmask` can be easily applied to many more pre-defined regions.

For all those datasets that dont have such a nice download API as NE, I created a yaml file https://github.com/mathause/regionmask/blob/f1705fabd759f0979a15b48822e15d75e1c3173a/download_regions.yaml that specifies the download location and how a `regionmask.Region` is generated. Downloads are cached in `~/.regionmask_data/[dataset_download_file_name]`. The notebook demonstrates this: https://github.com/mathause/regionmask/blob/f1705fabd759f0979a15b48822e15d75e1c3173a/demo_downloadshapefile.ipynb.

relates to #88, #42 

Closes #93 

Open questions:
- Is this implementation compatible to regionmask's design and intention? @mathause 

Todo:
- writing tests, currently notebook only checks for runthrough
- check doublicates
- docs

Future PRs:
- add more of such regions:
    - I accidentially came across http://maps.tnc.org/gis_data.html when searching for LME public urls. Could be nice to add more of such kind.
    - Also more regions that global climate modellers would use.

Possible shapefiles to add:
- FAO Fishing Areas: https://www.marineregions.org/downloads.php#fao
- EEZs: https://www.marineregions.org/sources.php#unioneezcountry
- IHO: https://www.marineregions.org/downloads.php#iho this looks similar to the PR of @jbusecke 
- Maritime Boundaries: https://www.marineregions.org/sources.php#marbound

I think this approach can be a great opportunity because it makes `regionmask` even more modular and easily extendible.

### CODE REVIEW

**Comment by mathause** [comment]
The region is actually called "MEOW" :D

---

That notebook is a great resource!

 1. A good start could be to create a `from_geopandas()` method (#42) - just like your `create_region_from_shapefile`. The difficulty is what to do with missing names and duplicate* names (https://github.com/mathause/regionmask/pull/94#issuecomment-605688621) and abbreviations. (Missing names are easier to fix).

\* Not having duplicates would be important for selecting regions and xarray (e.g. when assigning the names as coordinates to a mask). - Just add the region number?

2. What I had in mind (#88) was to create a "regionmask-data" repo, similar to the [xarray-data](https://github.com/pydata/xarray-data) repo ([code](https://github.com/pydata/xarray/blob/master/xarray/tutorial.py)). Which I might do for #61.

3. Your idea goes further to implement a general-purpose downloader. Which would be super helpful for e.g., #89. So I am interested to include something like this. The potential problems are (i) resources could just disappear, (ii) they could require a login (iii) the shapefile could change without notice. There'd need to be a clean way to add dataset-specific manipulations.

(iii) Could be addressed by adding an md5 sum.

---

> Is this implementation compatible to regionmask's design and intention?

Generally yes. There is quite a bit of logic behind the downloader. So it could be helpful to "steal" this logic, for example from [cartopy](https://github.com/SciTools/cartopy/blob/136a0470fa7bc55fa6485e1d42286eff02e1cd62/lib/cartopy/io/__init__.py#L86). I think I would probably have implemented the config in a *.py file; but why not a *.yaml file...

> implement into the source code: where? into regions.py or rather a new file?

I think `from_geopandas()` could probably go into `regions.py` the rest rather into a new file. `io.py`?

**Comment by aaronspring** [comment]
regarding 2. I understand the use of a new repo for different regions, although your manually created SREX or Giorgi regions are not large in datasize. However, the problem I see is licensing. Where do we take shapefiles from to upload them in a new repo. marineregions explicitly asks not to host the downloaded shapefiles from somewhere. therefore I went the detour of manually downloading.

**Comment by aaronspring** [comment]
regarding 3. i) yes disappearing resources can be a problem. then we would need to update the yaml. ii) because of these login issues, I would like to create the `from_geopandas` feature. with the folder `~/regionmask_data` this at least would only be needed once. iii) I always thought this md5 checksums are to check whether the downloadable dataset is identical to the downloaded one.

**Comment by aaronspring** [comment]
I will work on implementing 1) and io.py.

**Comment by mathause** [comment]
You can also have a look at

https://github.com/mathause/regionmask/blob/797b0b411c59df8fd1684371b9107288df62acb5/regionmask/defined_regions/natural_earth.py#L29

from L91

I thought the signature could be something like:


```python
def from_geopandas(
    geodataframe,
    numbers=None,
    names=None,
    abbrevs=None,
    name="unnamed",
    source=None,
    on_name_missing="error",
    on_name_duplicates="error",
    on_abbrev_missing="error",
    on_abbrev_duplicates="error",
):
```
but I am happy for other suggestions.

**Comment by aaronspring** [comment]
I do understand why I get these import errors in my tests locally. any idea? @mathause 

```
(xr) aaron.spring@Aarons-MBP:~/Coding/regionmask$ pytest
====================================================================== test session starts ======================================================================
platform darwin -- Python 3.7.3, pytest-4.4.1, py-1.8.0, pluggy-0.9.0
rootdir: /Users/aaron.spring/Coding/regionmask, inifile: setup.cfg
plugins: pylama-7.7.1
collected 0 items / 10 errors

============================================================================ ERRORS =============================================================================
_______________________________________________ ERROR collecting regionmask/test/test_OneRegion_and_Region_cls.py _______________________________________________
ImportError while importing test module '/Users/aaron.spring/Coding/regionmask/regionmask/test/test_OneRegion_and_Region_cls.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
regionmask/test/test_OneRegion_and_Region_cls.py:5: in <module>
    from regionmask import Region_cls, _OneRegion
E   ImportError: cannot import name '_OneRegion' from 'regionmask' (/Users/aaron.spring/anaconda3/envs/xr/lib/python3.7/site-packages/regionmask/__init__.py)
_______________________________________________________ ERROR collecting regionmask/test/test_Regions.py ________________________________________________________
ImportError while importing test module '/Users/aaron.spring/Coding/regionmask/regionmask/test/test_Regions.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
regionmask/test/test_Regions.py:6: in <module>
    from regionmask import Regions, _OneRegion
E   ImportError: cannot import name 'Regions' from 'regionmask' (/Users/aaron.spring/anaconda3/envs/xr/lib/python3.7/site-packages/regionmask/__init__.py)
_____________________________________________________ ERROR collecting regionmask/test/test_Regions_cls.py ______________________________________________________

**Comment by mathause** [comment]
Not to curb your motivation but I would prefer to add the `from_geopandas` function in a separate PR, including sufficient tests, and then continue with this. That feel like more logical pieces to me, and also makes it easier to review and test. Sorry, should have mentioned this before.

**Comment by aaronspring** [comment]
I can also make a from_geopandas PR first.

**Comment by aaronspring** [comment]
I think the main discussion point here for this PR should be the downloading approach: 
- from repo (+: sources wont disappear; -: licencing, more to maintain)
- from url (+: easily customizable; -: source can disappear)

or both?

**Comment by aaronspring** [comment]
#101 first

**Comment by aaronspring** [comment]
> I think the main discussion point here for this PR should be the downloading approach:
> 
>     * from repo (+: sources wont disappear; -: licencing, more to maintain)
> 
>     * from url (+: easily customizable; -: source can disappear)
> 
> 
> or both?

Any preference how to proceed here? I am in favor implementing both. and I would provide a PR for the from_url approach.

**Pull request closed without merging**
